spring.application.name=hospital-management-api
server.port=8081

server.error.include-message=always
server.error.include-binding-errors=always

# Konfigurimi i Databazës PostgreSQL duke përdorur Environment Variables nga Render
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfigurimi i JPA / Hibernate
# E vendosim perkohesisht ne "update" (ose "create" nese doni t'i rindërtoni nga zeroja) qe te shtoje automatikisht kolonat e reja si clinic_id
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect